[package]
name = "tracing-otel-init"
version = "0.2.2"
edition = "2021"
description = "Opinionated OpenTelemetry tracing initialization with OTLP export"
license = "MIT"

[features]
default = []
gzip-http = ["opentelemetry-otlp/gzip-http"]
rustls-tls = ["opentelemetry-otlp/reqwest-rustls"]
grpc = ["opentelemetry-otlp/grpc-tonic"]

[dependencies]
tracing = { version = "0.1.44", features = ["log"] }
tracing-subscriber = { version = "0.3.23", features = [
  "chrono",
  "env-filter",
  "json",
  "fmt",
  "std",
] }
tracing-opentelemetry = { version = "0.33.0", features = ["metrics"] }
opentelemetry = { version = "0.32.0", features = ["trace", "logs", "metrics"] }
opentelemetry-otlp = { version = "0.32.0", features = [
  "trace",
  "logs",
  "metrics",
  "http-proto",
  "reqwest-blocking-client",
] }
opentelemetry_sdk = { version = "0.32.0", features = [
  "rt-tokio",
  "trace",
  "logs",
  "metrics",
  "spec_unstable_metrics_views",
] }
opentelemetry-appender-tracing = { version = "0.32.0", features = [
  "experimental_span_attributes",
] }
tracing-appender = "0.2.5"
tracing-error = "0.2.1"
tracing-panic = "0.1.2"
thiserror = "2"

[dev-dependencies]
opentelemetry_sdk = { version = "0.32.0", features = ["testing"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
